version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fossawork-v2-db
    environment:
      POSTGRES_DB: fossawork_dev
      POSTGRES_USER: fossawork
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fossawork-v2-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local